homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret gps_lat
  longitude: !secret gps_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 80
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include_dir_merge_named components/customizations

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: !secret http_baseurl
  ssl_key: !secret http_key
  ssl_certificate: !secret http_cert
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

logger:
  default: warn
  logs:
    miio.device: critical

# Discover some devices automatically
# discovery:

cloud:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

input_select:
  alex_status_dropdown:
    name: Alex
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: warn

script: !include scripts.yaml
zwave: !include components/zwave.yaml
vacuum: !include components/vacuum.yaml
mysensors: !include components/mysensors/mysensors.yaml
#cover: !include components/garagedoor.yaml

sensor: !include_dir_merge_list components/sensor/
notify: !include_dir_merge_list components/notify/
media_player: !include_dir_merge_list components/media/
automation: !include_dir_merge_list components/automation/
group: !include_dir_merge_named components/group/
switch: !include_dir_merge_list components/switch/
shell_command: !include_dir_merge_named components/shell/

#google:
#  client_id: !secret google_clientid
#  client_secret: !secret google_secret

