- alias: Mark Alex as just arrived
  trigger:
    - platform: state
      entity_id: sensor.alex
      from: 'not_home'
      to: 'Home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.alex_status_dropdown
        option: Just Arrived
 
- alias: Mark Alex as home
  trigger:
    - platform: state
      entity_id: input_select.alex_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.alex_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  condition:
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.alex_status_dropdown
        option: Home
 
- alias: Mark Alex as just left
  trigger:
    - platform: state
      entity_id: sensor.alex
      from: 'Home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.alex_status_dropdown
        option: Just Left
 
- alias: Mark Alex as away
  trigger:
    - platform: state
      entity_id: input_select.alex_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.alex_status_dropdown
        option: Away

- alias: Mark Alex as extended away
  trigger:
    - platform: state
      entity_id: input_select.alex_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.alex_status_dropdown
        option: Extended Away