- alias: 'Light on kodi idle'
  trigger:
    - platform: state
      entity_id: media_player.kodi_living_room
      from: 'playing'
      to: 'idle'
    - platform: state
      entity_id: media_player.kodi_living_room
      from: 'paused'
      to: 'idle'
  condition:
  action:
    service: light.turn_on
    data:
      entity_id: group.light_main
      brightness_pct: 50