- alias: 'SSL expiry notification'
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.nma
    data:
      message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'